### ISSUE TITLE
import does not work in blender 4.5.0

### ISSUE THREAD

**Issue by dodov300** [space928/Blender-O3D-IO-Public#101]
Python: Traceback (most recent call last):
  File "C:\Users\ondra\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\Blender-O3D-IO-Public\__init__.py", line 133, in execute
    io_o3d_import.do_import(self.filepath, context, self.import_x, self.override_text_encoding, self.hide_lods)
  File "C:\Users\ondra\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\Blender-O3D-IO-Public\o3d_io\io_o3d_import.py", line 143, in do_import
    mesh.create_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'create_normals_split'

<img width="1129" height="235" alt="Image" src="https://github.com/user-attachments/assets/39635545-fdc4-441f-9322-64b2221b7c70" />

**Comment by space928** [comment]
Hi,
Unfortunately, Blender-O3D-IO doesn't support Blender 4 yet. As it stands,
I have a lot of other projects in development at the moment and
Blender-O3D-IO is in need of a full rewrite at some point (since starting
the project I have a much better understanding of how Omsi files work).
I hope to one day revisit this project and give it the update it deserves,
but for now I'm afraid you're stuck with using it in Blender 3.xx.

**Comment by dodov300** [comment]
Ok. I understand you at all.
